version: "3"
services:
  run:
    # replace username/repo:tag with your name and image details
    # container_name: "twcarto"
    image: twcarto:v0
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "35132:80"
    volumes:
      - "openstreetmap-data:/var/lib/postgresql/10/main"
      - "openstreetmap-rendered-tiles:/var/lib/mod_tile"
    networks:
      - webnet
    command: ["run"]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:
volumes:
  openstreetmap-data:
  openstreetmap-rendered-tiles:
